### ISSUE TITLE
Scan duration/timeout is not supported

### ISSUE THREAD

**Issue by avtr** [steamclock/bluejay#112]

**Comment by mdxs** [comment]
I'm actually wondering how to implement this now; as I've making a simple App which should scan for some devices for a while (so I want to stop/cancel scanning after a number of seconds). Allowing some interaction on devices (while scanning and/or after the scan). Actually a bit like the nRF Connect (from Nordic Semiconductor) is doing, which allows the user to set a scanner Timeout; and provides in top left corner a "Scan"/"Stop Scanning" button to toggle as well.

Should I try to hold on to the queued Scanner object in order to send a cancel/stop command?

**Comment by larryonoff** [comment]
Implemented in PR #125

**Comment by JeremyChiang** [comment]
Implemented by @larryonoff, thank you :)
