### ISSUE TITLE
Audit automatic endListen in SynchronizedPerhiperal

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#140]
I'm a bit worried that some edge failure cases in the synchronized peripheral could lead to double listens, because some of the endListens are skipped in some cases. I think I've convinced my self that the case I though was dangerous (it skipping it if bluetooth is turned off), is actually fine, but we have had some double listens showing up for unclear reasons in a client project (though it could be bugs in the client code as well). We should do a pass through and examine the behaviour of those more carefully and try and determine if there are any cases where it could fail to end a listen, and maybe reorganize the code so it's a bit less branchy.

**Comment by JeremyChiang** [comment]
Initial code review doesn't seem to indicate any end listen calls are skipped. Specifically, here are the calls that require calling end listen within:

`listen(to:timeout:completion:)`
`endListen(to:error:completion:)`
`flushListen(to:nonZeroTimeout:completion:)`
`writeAndListen(writeTo:value:type:listenTo:timeoutInSeconds:completion:)`
`writeAndAssemble(writeTo:value:listenTo:expectedLength:timeoutInSeconds:completion:)`

And all of these calls will try to end the listen if:
1. after the listen is installed, but times out and does not capture any value
2. or...after the listen is installed and the function completes successfully

Also, since v0.8.0, listens in `SynchornizedPeripheral` always trap by default to prevent unintentional or erroneous listen calls on a characteristic that Bluejay is already listening. The app will no longer crash as well, and the Bluejay background task would return with a clear error if this happens.
