### ISSUE TITLE
Does not work when used with BlueCapKit Framework

### ISSUE THREAD

**Issue by kaizenkaizen** [steamclock/bluejay#158]
import UIKit
import CoreBluetooth
import BlueCapKit
import Bluejay
I have these imports and run into this error:

'Peripheral' is ambiguous for type lookup in this context

and Bluejay.Peripheral does not work because: 'Peripheral' is not a member type of 'Bluejay'

**Comment by JeremyChiang** [comment]
Thanks for reporting this!

We found this post on stackoverflow and I've tested it as well: https://stackoverflow.com/questions/37892621/how-can-i-disambiguate-a-type-and-a-module-with-the-same-name

If you do something like the following it should work:

```
import BlueCapKit
import Bluejay
import class Bluejay.Peripheral

BlueCapKit.Peripheral.initialize()
Peripheral.initialize()
```

We will think more about whether we should rename the Bluejay manager class so that it is different from the name of the framework. It is probably a good idea, but since Swift does support these kinds of specific imports for this exact reason, one can argue it might not be necessary.

The important thing is you should be unblocked now and can use both Bluejay and BlueCapKit 🎉
