### ISSUE TITLE
how to get the CBPeripheral from the PeripheralIdentifier?

### ISSUE THREAD

**Issue by haemi** [steamclock/bluejay#199]
in an earlier version it was possible to get the CBPeripheral from peripherals, now after the scanning I do get DiscoveryResults and PeripheralIdentifiers, but I don't see how to get to the CBPeripheral...

**Comment by JeremyChiang** [comment]
Hi @haemi, it was a mistake exposing both `CBPeripheral` and the `Peripheral` references in Bluejay in the past, so they've been restricted since v0.8.0.

In theory, you shouldn't be working with a `CBPeripheral` handle when you are using Bluejay, because you could easily issue a read or write outside of Bluejay's context, and that would confuse and corrupt Bluejay's queueing states.

It's possible you can still do what you need to do without the `CBPeripheral` handle by using the available public API calls from Bluejay.
