### ISSUE TITLE
Get Cocoapod page set up

### ISSUE THREAD

**Issue by apike** [steamclock/bluejay#70]
Most CocoaPods have a page such as https://cocoapods.org/pods/BabyBluetooth. For more obscure pods (like, currently, Bluejay), the CocoaPods search just links to their github repo. I believe this involves getting our Pod Spec merged into the right place in the Specs repo: https://guides.cocoapods.org/making/specs-and-specs-repo.html. Currently the Spec link on CocoaPods for our spec is a 404: https://github.com/CocoaPods/Specs/tree/master/Specs/KIBluetooth/0.0.1/KIBluetooth.podspec.json

**Comment by JeremyChiang** [comment]
Turns out our pod spec was fine, but there's a [bug](https://github.com/CocoaPods/cocoapods.org/issues/265) on CocoaPod's server that won't trigger the page generation until you update the Pod once after publishing it.

All good now: https://cocoapods.org/pods/Bluejay

Documentation on CocoaPod page will take a while to generate. Might be able to point to jazzy docs instead as well, but I'll save that polish for a new and separate issue if needed.
